version: '3.4'
services:
  postgres_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=fcamaraDb
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - database-data:/var/lib/postgresql/data/
  pdadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fcamara.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80" 
    volumes:
      - pgadmin:/root/.pgadmin
  api:
    container_name: day_office_api
    ports:
      - "8080:80"
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres_database
  ui:
    container_name: day_office_ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
volumes:
  database-data:
  pgadmin:
