// <auto-generated />
using Day.Office.Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Day.Office.Api.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210909050939_EstacaoTrabalho-Seed")]
    partial class EstacaoTrabalhoSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Day.Office.Api.Entities.Escritorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("EstacoesDeTrabalho")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.ToTable("Escritorio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "São Paulo",
                            EstacoesDeTrabalho = 600,
                            Estado = "SP"
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "Santos",
                            EstacoesDeTrabalho = 100,
                            Estado = "SP"
                        });
                });

            modelBuilder.Entity("Day.Office.Api.Entities.EstacaoTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Estacao")
                        .HasColumnType("integer");

                    b.Property<int>("IdEscritorio")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdEscritorio");

                    b.ToTable("EstacaoTrabalho");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estacao = 1,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 2,
                            Estacao = 3,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 3,
                            Estacao = 5,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 4,
                            Estacao = 7,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 5,
                            Estacao = 9,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 6,
                            Estacao = 11,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 7,
                            Estacao = 13,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 8,
                            Estacao = 15,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 9,
                            Estacao = 17,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 10,
                            Estacao = 19,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 11,
                            Estacao = 21,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 12,
                            Estacao = 23,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 13,
                            Estacao = 25,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 14,
                            Estacao = 27,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 15,
                            Estacao = 29,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 16,
                            Estacao = 31,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 17,
                            Estacao = 33,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 18,
                            Estacao = 35,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 19,
                            Estacao = 37,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 20,
                            Estacao = 39,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 21,
                            Estacao = 41,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 22,
                            Estacao = 43,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 23,
                            Estacao = 45,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 24,
                            Estacao = 47,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 25,
                            Estacao = 49,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 26,
                            Estacao = 51,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 27,
                            Estacao = 53,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 28,
                            Estacao = 55,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 29,
                            Estacao = 57,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 30,
                            Estacao = 59,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 31,
                            Estacao = 61,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 32,
                            Estacao = 63,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 33,
                            Estacao = 65,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 34,
                            Estacao = 67,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 35,
                            Estacao = 69,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 36,
                            Estacao = 71,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 37,
                            Estacao = 73,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 38,
                            Estacao = 75,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 39,
                            Estacao = 77,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 40,
                            Estacao = 79,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 41,
                            Estacao = 81,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 42,
                            Estacao = 83,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 43,
                            Estacao = 85,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 44,
                            Estacao = 87,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 45,
                            Estacao = 89,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 46,
                            Estacao = 91,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 47,
                            Estacao = 93,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 48,
                            Estacao = 95,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 49,
                            Estacao = 97,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 50,
                            Estacao = 99,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 51,
                            Estacao = 101,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 52,
                            Estacao = 103,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 53,
                            Estacao = 105,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 54,
                            Estacao = 107,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 55,
                            Estacao = 109,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 56,
                            Estacao = 111,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 57,
                            Estacao = 113,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 58,
                            Estacao = 115,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 59,
                            Estacao = 117,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 60,
                            Estacao = 119,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 61,
                            Estacao = 121,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 62,
                            Estacao = 123,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 63,
                            Estacao = 125,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 64,
                            Estacao = 127,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 65,
                            Estacao = 129,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 66,
                            Estacao = 131,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 67,
                            Estacao = 133,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 68,
                            Estacao = 135,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 69,
                            Estacao = 137,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 70,
                            Estacao = 139,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 71,
                            Estacao = 141,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 72,
                            Estacao = 143,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 73,
                            Estacao = 145,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 74,
                            Estacao = 147,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 75,
                            Estacao = 149,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 76,
                            Estacao = 151,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 77,
                            Estacao = 153,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 78,
                            Estacao = 155,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 79,
                            Estacao = 157,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 80,
                            Estacao = 159,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 81,
                            Estacao = 161,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 82,
                            Estacao = 163,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 83,
                            Estacao = 165,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 84,
                            Estacao = 167,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 85,
                            Estacao = 169,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 86,
                            Estacao = 171,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 87,
                            Estacao = 173,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 88,
                            Estacao = 175,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 89,
                            Estacao = 177,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 90,
                            Estacao = 179,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 91,
                            Estacao = 181,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 92,
                            Estacao = 183,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 93,
                            Estacao = 185,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 94,
                            Estacao = 187,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 95,
                            Estacao = 189,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 96,
                            Estacao = 191,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 97,
                            Estacao = 193,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 98,
                            Estacao = 195,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 99,
                            Estacao = 197,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 100,
                            Estacao = 199,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 101,
                            Estacao = 201,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 102,
                            Estacao = 203,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 103,
                            Estacao = 205,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 104,
                            Estacao = 207,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 105,
                            Estacao = 209,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 106,
                            Estacao = 211,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 107,
                            Estacao = 213,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 108,
                            Estacao = 215,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 109,
                            Estacao = 217,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 110,
                            Estacao = 219,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 111,
                            Estacao = 221,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 112,
                            Estacao = 223,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 113,
                            Estacao = 225,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 114,
                            Estacao = 227,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 115,
                            Estacao = 229,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 116,
                            Estacao = 231,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 117,
                            Estacao = 233,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 118,
                            Estacao = 235,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 119,
                            Estacao = 237,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 120,
                            Estacao = 239,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 121,
                            Estacao = 241,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 122,
                            Estacao = 243,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 123,
                            Estacao = 245,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 124,
                            Estacao = 247,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 125,
                            Estacao = 249,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 126,
                            Estacao = 251,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 127,
                            Estacao = 253,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 128,
                            Estacao = 255,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 129,
                            Estacao = 257,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 130,
                            Estacao = 259,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 131,
                            Estacao = 261,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 132,
                            Estacao = 263,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 133,
                            Estacao = 265,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 134,
                            Estacao = 267,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 135,
                            Estacao = 269,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 136,
                            Estacao = 271,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 137,
                            Estacao = 273,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 138,
                            Estacao = 275,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 139,
                            Estacao = 277,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 140,
                            Estacao = 279,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 141,
                            Estacao = 281,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 142,
                            Estacao = 283,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 143,
                            Estacao = 285,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 144,
                            Estacao = 287,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 145,
                            Estacao = 289,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 146,
                            Estacao = 291,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 147,
                            Estacao = 293,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 148,
                            Estacao = 295,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 149,
                            Estacao = 297,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 150,
                            Estacao = 299,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 151,
                            Estacao = 301,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 152,
                            Estacao = 303,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 153,
                            Estacao = 305,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 154,
                            Estacao = 307,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 155,
                            Estacao = 309,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 156,
                            Estacao = 311,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 157,
                            Estacao = 313,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 158,
                            Estacao = 315,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 159,
                            Estacao = 317,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 160,
                            Estacao = 319,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 161,
                            Estacao = 321,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 162,
                            Estacao = 323,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 163,
                            Estacao = 325,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 164,
                            Estacao = 327,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 165,
                            Estacao = 329,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 166,
                            Estacao = 331,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 167,
                            Estacao = 333,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 168,
                            Estacao = 335,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 169,
                            Estacao = 337,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 170,
                            Estacao = 339,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 171,
                            Estacao = 341,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 172,
                            Estacao = 343,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 173,
                            Estacao = 345,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 174,
                            Estacao = 347,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 175,
                            Estacao = 349,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 176,
                            Estacao = 351,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 177,
                            Estacao = 353,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 178,
                            Estacao = 355,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 179,
                            Estacao = 357,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 180,
                            Estacao = 359,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 181,
                            Estacao = 361,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 182,
                            Estacao = 363,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 183,
                            Estacao = 365,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 184,
                            Estacao = 367,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 185,
                            Estacao = 369,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 186,
                            Estacao = 371,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 187,
                            Estacao = 373,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 188,
                            Estacao = 375,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 189,
                            Estacao = 377,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 190,
                            Estacao = 379,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 191,
                            Estacao = 381,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 192,
                            Estacao = 383,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 193,
                            Estacao = 385,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 194,
                            Estacao = 387,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 195,
                            Estacao = 389,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 196,
                            Estacao = 391,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 197,
                            Estacao = 393,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 198,
                            Estacao = 395,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 199,
                            Estacao = 397,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 200,
                            Estacao = 399,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 201,
                            Estacao = 401,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 202,
                            Estacao = 403,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 203,
                            Estacao = 405,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 204,
                            Estacao = 407,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 205,
                            Estacao = 409,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 206,
                            Estacao = 411,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 207,
                            Estacao = 413,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 208,
                            Estacao = 415,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 209,
                            Estacao = 417,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 210,
                            Estacao = 419,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 211,
                            Estacao = 421,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 212,
                            Estacao = 423,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 213,
                            Estacao = 425,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 214,
                            Estacao = 427,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 215,
                            Estacao = 429,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 216,
                            Estacao = 431,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 217,
                            Estacao = 433,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 218,
                            Estacao = 435,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 219,
                            Estacao = 437,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 220,
                            Estacao = 439,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 221,
                            Estacao = 441,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 222,
                            Estacao = 443,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 223,
                            Estacao = 445,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 224,
                            Estacao = 447,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 225,
                            Estacao = 449,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 226,
                            Estacao = 451,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 227,
                            Estacao = 453,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 228,
                            Estacao = 455,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 229,
                            Estacao = 457,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 230,
                            Estacao = 459,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 231,
                            Estacao = 461,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 232,
                            Estacao = 463,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 233,
                            Estacao = 465,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 234,
                            Estacao = 467,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 235,
                            Estacao = 469,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 236,
                            Estacao = 471,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 237,
                            Estacao = 473,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 238,
                            Estacao = 475,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 239,
                            Estacao = 477,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 240,
                            Estacao = 479,
                            IdEscritorio = 1
                        },
                        new
                        {
                            Id = 241,
                            Estacao = 1,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 242,
                            Estacao = 3,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 243,
                            Estacao = 5,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 244,
                            Estacao = 7,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 245,
                            Estacao = 9,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 246,
                            Estacao = 11,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 247,
                            Estacao = 13,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 248,
                            Estacao = 15,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 249,
                            Estacao = 17,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 250,
                            Estacao = 19,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 251,
                            Estacao = 21,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 252,
                            Estacao = 23,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 253,
                            Estacao = 25,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 254,
                            Estacao = 27,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 255,
                            Estacao = 29,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 256,
                            Estacao = 31,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 257,
                            Estacao = 33,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 258,
                            Estacao = 35,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 259,
                            Estacao = 37,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 260,
                            Estacao = 39,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 261,
                            Estacao = 41,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 262,
                            Estacao = 43,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 263,
                            Estacao = 45,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 264,
                            Estacao = 47,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 265,
                            Estacao = 49,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 266,
                            Estacao = 51,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 267,
                            Estacao = 53,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 268,
                            Estacao = 55,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 269,
                            Estacao = 57,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 270,
                            Estacao = 59,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 271,
                            Estacao = 61,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 272,
                            Estacao = 63,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 273,
                            Estacao = 65,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 274,
                            Estacao = 67,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 275,
                            Estacao = 69,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 276,
                            Estacao = 71,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 277,
                            Estacao = 73,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 278,
                            Estacao = 75,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 279,
                            Estacao = 77,
                            IdEscritorio = 2
                        },
                        new
                        {
                            Id = 280,
                            Estacao = 79,
                            IdEscritorio = 2
                        });
                });

            modelBuilder.Entity("Day.Office.Api.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Day.Office.Api.Entities.EstacaoTrabalho", b =>
                {
                    b.HasOne("Day.Office.Api.Entities.Escritorio", "Escritorio")
                        .WithMany("EstacoesTrabalho")
                        .HasForeignKey("IdEscritorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escritorio");
                });

            modelBuilder.Entity("Day.Office.Api.Entities.Escritorio", b =>
                {
                    b.Navigation("EstacoesTrabalho");
                });
#pragma warning restore 612, 618
        }
    }
}
